---
- name: Install Python 2 on target machine
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - raw: sudo apt-get update -qq && sudo apt-get install -qq python

- name: Set up servers
  hosts: all
  become: true
  roles:
    - name: common-server
      COMMON_SERVER_NO_BACKUPS: true
    - name: 'pmbauer.tarsnap'

- name: Install backup pruner
  hosts: all
  become: true
  tasks:
    - include: backup-pruner.yml