
FORWARD_MAIL_RELAY_MAIL_TO: "ops@example.com"
FORWARD_MAIL_SMTP_FROM: "{{ FORWARD_MAIL_RELAY_MAIL_TO }}"

TARSNAPPER_CONF: /etc/tarsnapper.yml

# Can be changed to normal tarsnapper once we merge this branch
# and code winds up on PIP
TARSNAPPER_VERSION: git+https://github.com/open-craft/tarsnapper@jbzdak/tarsnapper-extensions

keys_to_upload:
  - name: "mysql-backup"
    keypath: "/etc/keyfile"
    key: "{{ VARIABLE_CONTAINING_TARSNAP_KEY }}"
    cache: "/var/cache/tarsnap"

TARSNAPPER_CONFIG_CONTENTS:
  jobs:
    mysql-backup:
      sources: []
      target: mysql-$date
      keyfile: "/etc/keyfile"
      cachedir: "/var/cache/tarsnap"
      deltas: 1h 1d 7d 30d 360d 18000d
